// PR #497 only: exclude removed files while reviewing every surviving change.
import { defineConfig } from "@coderabbitai/config";

export default defineConfig((ctx) => {
  if (ctx.repo.fullName !== "TypeWhisper/typewhisper-win" || ctx.pr?.number !== 497) return {};
  return {
    reviews: {
      path_filters: [
        "!.github/scripts/**",
        "!.github/workflows/publish-plugins.yml",
        "!.github/workflows/release.yml",
        "!docs/WINDOWS_UI_AUTOMATION.md",
        "!docs/screenshots/windows/**",
        "!eng/Capture-WindowsScreenshots.ps1",
        "!eng/ui-automation/**",
        "!plugins/TypeWhisper.Plugin.AssemblyAi/**",
        "!plugins/TypeWhisper.Plugin.AuthenticatedCli/**",
        "!plugins/TypeWhisper.Plugin.Cerebras/**",
        "!plugins/TypeWhisper.Plugin.Claude/**",
        "!plugins/TypeWhisper.Plugin.CloudflareAsr/**",
        "!plugins/TypeWhisper.Plugin.Cohere/**",
        "!plugins/TypeWhisper.Plugin.CohereTranscribe/**",
        "!plugins/TypeWhisper.Plugin.Deepgram/DeepgramPlugin.cs",
        "!plugins/TypeWhisper.Plugin.Deepgram/DeepgramSettingsView.xaml",
        "!plugins/TypeWhisper.Plugin.Deepgram/DeepgramSettingsView.xaml.cs",
        "!plugins/TypeWhisper.Plugin.Deepgram/DeepgramStreamingSession.cs",
        "!plugins/TypeWhisper.Plugin.Deepgram/manifest.portable.json",
        "!plugins/TypeWhisper.Plugin.ElevenLabs/**",
        "!plugins/TypeWhisper.Plugin.FileMemory/**",
        "!plugins/TypeWhisper.Plugin.FillerWords/FillerWordsSettingsView.xaml",
        "!plugins/TypeWhisper.Plugin.FillerWords/FillerWordsSettingsView.xaml.cs",
        "!plugins/TypeWhisper.Plugin.FillerWords/Tests/FillerWordsPluginTests.cs",
        "!plugins/TypeWhisper.Plugin.Fireworks/**",
        "!plugins/TypeWhisper.Plugin.Gemini/**",
        "!plugins/TypeWhisper.Plugin.GemmaLocal/**",
        "!plugins/TypeWhisper.Plugin.Gladia/**",
        "!plugins/TypeWhisper.Plugin.GoogleCloudStt/**",
        "!plugins/TypeWhisper.Plugin.GraniteSpeech/**",
        "!plugins/TypeWhisper.Plugin.Groq/GroqSettingsView.xaml",
        "!plugins/TypeWhisper.Plugin.Groq/GroqSettingsView.xaml.cs",
        "!plugins/TypeWhisper.Plugin.Groq/manifest.portable.json",
        "!plugins/TypeWhisper.Plugin.Linear/**",
        "!plugins/TypeWhisper.Plugin.LiveTranscript/**",
        "!plugins/TypeWhisper.Plugin.Meta/**",
        "!plugins/TypeWhisper.Plugin.MicrosoftAi/**",
        "!plugins/TypeWhisper.Plugin.Obsidian/ObsidianSettingsView.xaml",
        "!plugins/TypeWhisper.Plugin.Obsidian/ObsidianSettingsView.xaml.cs",
        "!plugins/TypeWhisper.Plugin.OpenAi/**",
        "!plugins/TypeWhisper.Plugin.OpenAiCompatible/**",
        "!plugins/TypeWhisper.Plugin.OpenAiVectorMemory/**",
        "!plugins/TypeWhisper.Plugin.OpenRouter/**",
        "!plugins/TypeWhisper.Plugin.ParakeetCtc/manifest.portable.json",
        "!plugins/TypeWhisper.Plugin.Qwen3Stt/**",
        "!plugins/TypeWhisper.Plugin.Reson8/**",
        "!plugins/TypeWhisper.Plugin.Script/**",
        "!plugins/TypeWhisper.Plugin.SherpaOnnx/manifest.portable.json",
        "!plugins/TypeWhisper.Plugin.SmallestAi/**",
        "!plugins/TypeWhisper.Plugin.Soniox/**",
        "!plugins/TypeWhisper.Plugin.Speechmatics/**",
        "!plugins/TypeWhisper.Plugin.SupertonicTts/**",
        "!plugins/TypeWhisper.Plugin.Voxtral/**",
        "!plugins/TypeWhisper.Plugin.Webhook/**",
        "!plugins/TypeWhisper.Plugin.WhisperCpp/**",
        "!plugins/TypeWhisper.Plugin.Xai/**",
        "!src/TypeWhisper.PluginSDK.Portable/**",
        "!src/TypeWhisper.Windows/**",
        "!tests/TypeWhisper.Clipboard.LiveTests/**",
        "!tests/TypeWhisper.Clipboard.Probe/**",
        "!tests/TypeWhisper.PluginSystem.Tests/**",
        "!tools/TypeWhisper.UiAutomation/**",
      ],
    },
  };
});
