namespace TypeWhisper.Plugin.Gemini;

public sealed partial class GeminiPlugin
{
    // ISO picker codes and supported BCP-47 defaults, verified 2026-09-18:
    // https://ai.google.dev/gemini-api/docs/transcribe#supported-languages
    private static readonly Dictionary<string, string> LanguageCodes = new(StringComparer.OrdinalIgnoreCase)
    {
        ["af"] = "af-ZA",
        ["am"] = "am-ET",
        ["ar"] = "ar-EG",
        ["as"] = "as-IN",
        ["az"] = "az-AZ",
        ["be"] = "be-BY",
        ["bg"] = "bg-BG",
        ["bn"] = "bn-BD",
        ["bs"] = "bs-BA",
        ["ca"] = "ca-ES",
        ["ceb"] = "ceb",
        ["cs"] = "cs-CZ",
        ["da"] = "da-DK",
        ["de"] = "de-DE",
        ["el"] = "el-GR",
        ["en"] = "en-US",
        ["es"] = "es-419",
        ["et"] = "et-EE",
        ["fa"] = "fa-IR",
        ["fi"] = "fi-FI",
        ["fil"] = "fil-PH",
        ["fr"] = "fr-FR",
        ["gl"] = "gl-ES",
        ["gu"] = "gu-IN",
        ["ha"] = "ha-NG",
        ["he"] = "he-IL",
        ["hi"] = "hi-IN",
        ["hr"] = "hr-HR",
        ["hu"] = "hu-HU",
        ["hy"] = "hy-AM",
        ["id"] = "id-ID",
        ["is"] = "is-IS",
        ["it"] = "it-IT",
        ["ja"] = "ja-JP",
        ["jv"] = "jv-ID",
        ["ka"] = "ka-GE",
        ["kea"] = "kea-CV",
        ["kk"] = "kk-KZ",
        ["km"] = "km-KH",
        ["kn"] = "kn-IN",
        ["ko"] = "ko-KR",
        ["ky"] = "ky-KG",
        ["ln"] = "ln-CD",
        ["lt"] = "lt-LT",
        ["lv"] = "lv-LV",
        ["mk"] = "mk-MK",
        ["ml"] = "ml-IN",
        ["mn"] = "mn-MN",
        ["mr"] = "mr-IN",
        ["ms"] = "ms-MY",
        ["mt"] = "mt-MT",
        ["my"] = "my-MM",
        ["nb"] = "nb-NO",
        ["ne"] = "ne-NP",
        ["nl"] = "nl-NL",
        ["no"] = "nb-NO",
        ["or"] = "or-IN",
        ["pa"] = "pa-IN",
        ["pl"] = "pl-PL",
        ["pt"] = "pt-BR",
        ["ro"] = "ro-RO",
        ["ru"] = "ru-RU",
        ["rup"] = "rup-BG",
        ["sd"] = "sd-Arab-IN",
        ["sk"] = "sk-SK",
        ["sl"] = "sl-SI",
        ["sr"] = "sr-RS",
        ["sv"] = "sv-SE",
        ["sw"] = "sw-KE",
        ["te"] = "te-IN",
        ["tg"] = "tg-TJ",
        ["th"] = "th-TH",
        ["tr"] = "tr-TR",
        ["uk"] = "uk-UA",
        ["uz"] = "uz-UZ",
        ["vi"] = "vi-VN",
        ["yue"] = "yue-Hant-HK",
        ["zh"] = "cmn-Hans-CN",
    };

    /// <inheritdoc />
    public IReadOnlyList<string> SupportedLanguages => LanguageCodes.Keys.ToArray();
}
